"use client";

import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";

type Locale = "tr" | "en";

// Reviewed public copy. This intentionally avoids automatic translation.
const en: Record<string, string> = {
  "Ana Sayfa": "Home", "Hizmetler": "Services", "Projeler": "Projects", "Hakkımızda": "About Us", "Kataloglar": "Catalogues", "İletişim": "Contact", "Teklif Al": "Get an Offer", "Ücretsiz Keşif": "Free Site Survey", "Hizmetlerimiz": "Our Services", "Braas Yetkili Bayisi": "Braas Authorised Dealer",
  "Antalya'nın Güvenilir Çatı Çözüm Ortağı": "Antalya’s Trusted Roofing Partner", "Antalya'nın": "Antalya’s", "Güvenilir": "Trusted", "Çatı Çözüm Ortağı": "Roofing Solutions Partner", "Çatı sistemlerinde bütüncül uygulama.": "A complete approach to roofing systems.", "Karot Mimarlık": "Karot Architecture", "Yetkili Çözüm Ortağı": "Authorised Solution Partner", "Ürün garantisi*": "Product warranty*", "ve çevre iller": "and neighbouring provinces",
  "Antalya ve çevre illerde; yeni çatı uygulamaları, yenileme ve yalıtım çözümlerini yapınızın teknik gereksinimlerine göre planlıyoruz.": "Across Antalya and neighbouring provinces, we plan new roofs, renovations and insulation solutions around your building’s technical requirements.", "Kaplama, yalıtım ve tamamlayıcı detayları aynı sistem yaklaşımıyla ele alıyoruz.": "We coordinate covering, insulation and every finishing detail as one integrated system.",
  "Keşiften teslimata": "From survey to completion", "Nitelikli bir çatı, doğru analiz ve planlamayla başlar.": "A high-performing roof begins with sound analysis and planning.", "Her yapının ihtiyacı farklıdır. Mevcut koşulları yerinde değerlendiriyor; malzeme seçimi ve uygulama detaylarını bu teknik veriye göre oluşturuyoruz.": "Every building has different needs. We assess conditions on site, then define materials and installation details from that technical evidence.", "Tüm hizmetleri incele": "Explore all services", "Yerinde keşif": "On-site survey", "Sistemi planlama": "System planning", "Uygulama ve takip": "Installation and follow-up", "Çatı eğimi, mevcut katmanlar, su tahliyesi ve kritik birleşim noktalarını yerinde değerlendiriyoruz.": "We assess roof pitch, existing layers, drainage and critical junctions on site.", "Kaplama, yalıtım, havalandırma ve yağmur suyu detaylarını yapının ihtiyaçlarına göre birlikte planlıyoruz.": "We coordinate covering, insulation, ventilation and rainwater details around the building’s needs.", "Uygulama sürecini sahada takip ediyor; katmanlar ve birleşim detayları arasındaki uyumu kontrol ediyoruz.": "We monitor installation on site and verify the coordination of layers and junction details.",
  "Karot Mimarlık farkı": "The Karot Mimarlık difference", "Çatınızı, birbiriyle uyum içinde çalışan bir sistem olarak planlıyoruz.": "We plan your roof as a system whose parts perform together.", "Malzeme seçimi, uygulama kalitesi ve iklim koşullarına uygun detaylar; çatı sisteminin performansını birlikte belirler.": "Material choice, installation quality and climate-appropriate details together determine roof-system performance.", "Sistem uyumu": "System coordination", "Doğru uygulama": "Precision installation", "Yerinde değerlendirme": "On-site assessment", "Bölgesel tecrübe": "Regional experience", "Garantili İşçilik": "Assured workmanship", "Antalya ve Çevre İller": "Antalya and neighbouring provinces",
  "Braas çatı sistemlerini yalnızca kaplama malzemesi olarak değil; havalandırma, mahya ve tamamlayıcı bileşenleriyle bir bütün olarak ele alıyoruz.": "We view Braas roofing systems as more than a covering: ventilation, ridge and complementary components are planned as one whole.", "Çatının dayanımı, malzeme kadar birleşim noktalarındaki işçiliğe de bağlıdır. Mahya, baca dibi, dere ve saçak detaylarını titizlikle ele alıyoruz.": "A roof’s durability depends as much on workmanship at its junctions as on its materials. We handle ridge, chimney, valley and eaves details with care.", "Uygulamaya başlamadan önce mevcut çatıyı yerinde inceliyor; su alma, ısı kaybı, taşıyıcı sistem ve yenileme ihtiyacını netleştiriyoruz.": "Before work begins, we inspect the existing roof on site and clarify water ingress, heat loss, structure and renovation needs.", "Antalya'nın yoğun güneş, ani yağış ve rüzgar koşullarını dikkate alarak çatı katmanlarını ve uygulama detaylarını planlıyoruz.": "We plan roof layers and installation details for Antalya’s intense sun, sudden rain and wind conditions.",
  "Ücretsiz ön değerlendirme": "Free initial assessment", "Çatı projeniz için teklif talep edin.": "Request a quote for your roofing project.", "Yapınız ve ihtiyacınız hakkında temel bilgileri paylaşın. Talebiniz doğrudan ekibimize iletilir; değerlendirme sonrasında sizinle iletişime geçeriz.": "Share the essentials about your building and requirements. Your request goes directly to our team and we will contact you after review.", "Yeni çatı, yenileme veya yalıtım ihtiyacınızı belirtin.": "Tell us whether you need a new roof, renovation or insulation.", "Konum ve yaklaşık metrekare bilgisini ekleyin.": "Add the location and approximate square metres.", "Dilerseniz WhatsApp üzerinden fotoğraf ve ek detay paylaşın.": "You can also share photos and further details via WhatsApp.", "Ad soyad *": "Full name *", "Adınız ve soyadınız": "Your full name", "Telefon *": "Phone *", "E-posta *": "Email *", "Proje konumu *": "Project location *", "Hizmet türü *": "Service required *", "Yaklaşık çatı alanı": "Approximate roof area", "Proje detayları": "Project details", "Seçiniz": "Select", "Yeni çatı yapımı": "New roof construction", "Çelik çatı konstrüksiyonu": "Steel roof structure", "Çatı yenileme": "Roof renovation", "Su ve ısı yalıtımı": "Waterproofing and thermal insulation", "Braas çatı sistemi": "Braas roofing system", "Bakım / onarım": "Maintenance / repair", "Henüz bilmiyorum": "I do not know yet", "Mevcut çatı durumu, beklentiniz veya paylaşmak istediğiniz diğer bilgiler...": "Existing roof condition, your requirements, or anything else you would like to share…", "Paylaştığım bilgilerin teklif talebimin değerlendirilmesi ve benimle iletişime geçilmesi amacıyla kullanılmasını kabul ediyorum.": "I consent to the use of my information to assess this quote request and contact me.", "Teklif talebini gönder →": "Send quote request →", "Talebiniz e-posta yoluyla ekibimize iletilir. İlk gönderimden sonra e-posta yönlendirmesini etkinleştirmeniz istenebilir.": "Your request is sent to our team by email. After the first submission, you may be asked to activate email forwarding.",
  "Çalışma alanları": "Areas of expertise", "İletişim ve keşif": "Contact and site survey", "Bütünleşik kaplama ve detay çözümleri": "Integrated covering and detail solutions", "Taşıyıcı sistemden son katmana uygulama": "Installation from structure to final layer", "Mevcut çatılar için onarım ve dönüşüm": "Repair and renewal for existing roofs", "Nem, yoğuşma ve ısı kaybına karşı katmanlar": "Layers against moisture, condensation and heat loss", "Projenizi birlikte değerlendirelim.": "Let’s assess your project together.", "İlk görüşmede ihtiyaçlarınızı dinliyor, yerinde keşif sonrasında çatınız için uygulanabilir sistem alternatiflerini paylaşıyoruz.": "We listen to your requirements first, then share practical system options for your roof following an on-site survey.", "Telefon": "Phone", "E-posta": "Email", "Hizmet bölgesi": "Service area", "Antalya ve çevre iller": "Antalya and neighbouring provinces", "WhatsApp'tan Yaz": "Message us on WhatsApp", "Tüm hakları saklıdır.": "All rights reserved.",
  "İhtiyacınıza uygun profesyonel çatı çözümleri.": "Professional roofing solutions tailored to your needs.", "Antalya ve çevre illerde; yeni çatı, yenileme ve yalıtım uygulamalarını yapınızın mimari ve teknik gereksinimlerine göre planlıyor, sahada uyguluyoruz.": "Across Antalya and neighbouring provinces, we plan and install new roofs, renovations and insulation to meet your building’s architectural and technical requirements.", "Sistem odaklı uygulama": "System-led installation", "Çatının her katmanı için doğru çözüm.": "The right solution for every roof layer.", "Kaplama, yalıtım, mahya detayları ve yağmur suyu yönetimini aynı uygulama planı içinde değerlendiriyoruz.": "We coordinate covering, insulation, ridge details and rainwater management within one installation plan.", "Çalışma Alanlarımız": "Our Areas of Expertise", "Size sunduğumuz hizmetler": "Services for your project", "Yapının mevcut durumu, mimari beklentileri ve iklim koşullarına göre uygun sistemi belirliyor; uygulama sürecini planlı biçimde yönetiyoruz.": "We determine the right system from the building’s condition, architectural expectations and climate, then manage installation in a planned way.",
  "Braas Çatı Sistemleri": "Braas Roofing Systems", "Çatı Yapımı": "New Roof Construction", "Çatı Yenileme": "Roof Renovation", "Çatı İzolasyonu": "Roof Insulation", "Kiremit Çatı Uygulamaları": "Tile Roof Installation", "Çelik Çatı Konstrüksiyonu": "Steel Roof Structure", "Profesyonel Çatı Çözümleri": "Professional Roofing Solutions", "Sistem yaklaşımımız": "Our system approach", "İyi bir çatı, sadece kiremitten oluşmaz.": "A good roof is more than tiles.", "Projenizi Konuşalım": "Let’s talk about your project", "Çatınız için uygun sistemi birlikte planlayalım.": "Let’s plan the right system for your roof together.", "Projeniz için ön değerlendirme ve ücretsiz keşif talebi oluşturmak üzere bizimle iletişime geçebilirsiniz.": "Contact us to request an initial review and free site survey for your project.", "WhatsApp'tan İletişime Geç": "Contact us on WhatsApp",
  "Projelerimiz": "Our Projects", "Gerçek projeler, gerçek çatı çözümleri.": "Real projects, considered roofing solutions.", "Antalya ve çevre illerde, farklı yapı tipleri için gerçekleştirdiğimiz çatı uygulamalarından seçilmiş saha örnekleri.": "A selection of on-site roofing applications we have completed for different building types across Antalya and neighbouring provinces.", "Çalışmalarımız": "Our work", "Uygulama portföyümüz": "Our installation portfolio", "Her çalışmada; yapının teknik ihtiyacına, çatı eğimine ve uygulama detaylarına göre şekillenen farklı çözüm aşamalarını görebilirsiniz.": "Each project shows solution stages tailored to the building’s technical needs, roof pitch and installation details.", "Saha uygulaması ↗": "On-site installation ↗", "Uygulama metodumuz": "Our installation method", "Her proje, doğru teknik kararlarla şekillenir.": "Every project is shaped by sound technical decisions.", "Portföyde yer alan her uygulamanın arkasında; saha incelemesi, uygun sistem bileşenlerinin seçimi ve kritik detayların kontrolü bulunur.": "Behind every application in this portfolio are site assessment, appropriate component selection and control of critical details.", "Projeniz için ilk adım": "The first step for your project", "Çatı projenizi birlikte değerlendirelim.": "Let’s assess your roofing project together.", "Yapınızın ihtiyaçlarını görüşmek ve ücretsiz keşif talebinizi iletmek için bizimle iletişime geçebilirsiniz.": "Contact us to discuss your building’s needs and request a free site survey.",
  "Çatı konusunda uzmanlığımız.": "Our roofing expertise.", "Bizimle İletişime Geç →": "Contact us →", "Projelerimizi Gör": "View our projects", "Karot Mimarlık yaklaşımı": "The Karot Mimarlık approach", "Doğru detay, uzun ömürlü sonuç.": "The right detail, built to last.", "Sektör deneyimi": "Industry experience", "Ürün özellikleri garantisi*": "Product-performance warranty*", "ve çevre illerde hizmet": "serving Antalya and neighbouring provinces", "Hikayemiz": "Our story", "Güvenilir işçilik, uzun ömürlü çözümler.": "Reliable workmanship, long-lasting solutions.", "Kaliteli İşçilik": "Quality workmanship", "Doğru Malzeme": "Appropriate materials", "Güvenilir Hizmet": "Dependable service", "Uzun Ömürlü": "Built to last", "Yetkili Bayi": "Authorised Dealer", "Hizmetlerimizi İncele →": "Explore our services →", "Neden Biz?": "Why choose us?", "Projenizde güvenebileceğiniz bir çözüm ortağı.": "A solution partner you can rely on for your project.", "Deneyim": "Experience", "Bölgesel Hizmet": "Regional service",
  "Teknik dokümanlara doğrudan erişim.": "Direct access to technical documents.", "Braas Çatı Sistemleri'nin ürün, uygulama ve teknik detay kataloglarını resmî kaynağından inceleyin.": "Browse Braas Roofing Systems product, installation and technical-detail catalogues from the official source.", "Resmî Braas Kaynakları ↗": "Official Braas Resources ↗", "Kataloglar BMI Group Türkiye'nin resmî doküman merkezi üzerinden güncel olarak sunulur.": "Catalogues are kept current through BMI Group Türkiye’s official document centre.", "Doküman merkezi": "Document centre", "Projeniz için ilgili kaynağı inceleyin.": "Explore the relevant resource for your project.", "Resmî kaynağa git →": "Go to official source →",
  "Bize Ulaşın": "Contact us", "İletişim Bilgilerimiz": "Our Contact Details", "Projenizi birlikte konuşalım.": "Let’s discuss your project.", "Projenizi": "Your project", "birlikte konuşalım": "let’s discuss it", "Çatı yapımı, yenileme veya izolasyon projeniz için bizimle iletişime geçebilir, ücretsiz keşif ve detaylı bilgi alabilirsiniz.": "Contact us for a new roof, renovation or insulation project, and receive a free site survey and detailed information.", "30 YIL": "30 YEARS", "ÜRÜN GARANTİSİ": "PRODUCT WARRANTY", "Suya ve dona karşı güvence": "Protection against water and frost", "YETKİLİ BAYİ": "AUTHORISED DEALER", "Orijinal ürün ve profesyonel hizmet": "Genuine products and professional service", "VE ÇEVRESİ": "AND SURROUNDING AREA", "Hızlı keşif ve yerinde çözüm": "Prompt survey and on-site solution", "Bize doğrudan ulaşın": "Contact us directly", "HEMEN ARA": "CALL NOW", "Sorularınız için yazın": "Write to us with your questions", "E-POSTA GÖNDER": "SEND EMAIL", "Adres": "Address", "Ziyaret etmek isterseniz": "If you would like to visit"
};

Object.assign(en, {
  "Kaplama": "Roof Covering", "Su ve Isı Yalıtımı": "Waterproofing and Thermal Insulation", "Mahya ve Detaylar": "Ridge and Detail Work", "Yağmur Suyu Yönetimi": "Rainwater Management",
  "Kiremit modeli; çatının eğimi, mimari dili ve iklim koşulları dikkate alınarak belirlenir.": "The tile profile is selected with the roof pitch, architectural character and local climate conditions in mind.",
  "Çatı altı katmanları, yoğuşma ve dış etken kaynaklı nem riskine karşı sistemin sürekliliğini destekler.": "Sub-roof layers support continuous system performance against condensation and moisture caused by external conditions.",
  "Baca dibi, mahya, dere ve kenar birleşimleri; uzun ömürlü bir çatının en kritik noktalarıdır.": "Chimney, ridge, valley and edge junctions are among the most critical details of a long-lasting roof.",
  "Oluk ve indirme elemanları, suyun yapıdan kontrollü biçimde uzaklaştırılmasına yardımcı olur.": "Gutters and downpipes help direct rainwater safely away from the building.",
  "2007'den bu yana Antalya ve çevre illerde, yapıların ihtiyaçlarına özel çatı, yenileme ve yalıtım çözümlerini teknik uzmanlıkla uyguluyoruz.": "Since 2007, we have delivered technically considered roofing, renovation and insulation solutions tailored to each building across Antalya and the surrounding region.",
  "Braas yetkili bayisi olarak, kaplama ve tamamlayıcı bileşenleri birbiriyle uyumlu sistem yaklaşımıyla uyguluyoruz.": "As a Braas authorised dealer, we install covering and complementary components as a coordinated system.",
  "Kiremit model ve renk seçimi": "Tile model and colour selection", "Mahya ve kenar detayları": "Ridge and edge details", "Sistem bileşenlerinin uyumu": "Component coordination",
  "Yeni yapılarda taşıyıcı sistemden kaplama katmanına kadar, projeye uygun çatı uygulamaları gerçekleştiriyoruz.": "For new buildings, we deliver roof installations from the structural system through to the covering layer.",
  "Yeni yapı çatısı": "New-build roof", "Taşıyıcı sisteme uygun çözüm": "Solution suited to the supporting structure", "Uygulama planlaması": "Installation planning",
  "Mevcut çatılarda ihtiyaç analizi yapıyor; yıpranan katmanları ve kritik detayları uygun uygulama planıyla yeniliyoruz.": "We assess existing roofs, then renew worn layers and critical details through an appropriate installation plan.",
  "Hasar ve sızıntı tespiti": "Damage and leak assessment", "Yıpranan katmanların yenilenmesi": "Renewal of worn layers", "Detay noktalarının iyileştirilmesi": "Improvement of critical details",
  "Su ve ısı yalıtımı katmanlarını; nem, yoğuşma ve ısı kaybı risklerini dikkate alarak planlıyoruz.": "We plan waterproofing and thermal-insulation layers around moisture, condensation and heat-loss risks.",
  "Nefes alan su yalıtımı": "Breathable waterproofing", "Isı kaybını azaltan katmanlar": "Heat-loss-reducing layers", "Yoğuşma riskine karşı planlama": "Planning against condensation risk",
  "Yapının mimari karakterine ve çatı eğimine uygun kiremit uygulamalarını, tamamlayıcı detaylarla birlikte gerçekleştiriyoruz.": "We install tiles that suit the building’s architectural character and roof pitch, together with all complementary details.",
  "Model ve doku seçimi": "Model and texture selection", "Mahya, dere ve saçak detayları": "Ridge, valley and eaves details", "Estetik ile dayanıklılık dengesi": "Balance of aesthetics and durability",
  "Yapının statik gereksinimleri doğrultusunda; çelik taşıyıcı sistem, aşık yerleşimi ve bağlantı detaylarını uygulama sürecine uygun biçimde planlıyoruz.": "In line with structural requirements, we plan the steel supporting system, purlin layout and connection details for installation.",
  "Çelik taşıyıcı sistem kurulumu": "Steel supporting-system installation", "Aşık ve bağlantı detayları": "Purlin and connection details", "Kaplama sistemine uygun hazırlık": "Preparation for the covering system",
  "Antalya ve çevre illerde, yapınızın mevcut durumu ve kullanım gereksinimlerine göre çatı çözümleri geliştiriyoruz.": "Across Antalya and neighbouring provinces, we develop roofing solutions around your building’s condition and use requirements.",
  "Ücretsiz ilk değerlendirme": "Free initial review", "Proje özelinde sistem önerisi": "Project-specific system proposal", "Saha uygulama takibi": "On-site installation monitoring",
  "Ahşap Taşıyıcı Çatı Konstrüksiyonu": "Timber Roof Structure", "Yalıtım Katmanları ve Kaplama Altı Sistem": "Insulation Layers and Underlay System", "Çatı Yenileme ve Lata Uygulaması": "Roof Renovation and Batten Installation", "Kiremitli Villa Çatısı": "Tiled Villa Roof", "Braas Kiremit Sistem Uygulaması": "Braas Tile System Installation",
  "Yeni yapı için hazırlanan ahşap taşıyıcı sistemin, çatı eğimi ve baca geçişleri dikkate alınarak oluşturulması.": "A timber structural system designed for a new building with roof pitch and chimney penetrations considered.",
  "Su yalıtım örtüsü, ısı yalıtım levhası ve kaplama altı bileşenlerinin bir arada ele alındığı uygulama aşaması.": "An installation stage where waterproofing membrane, thermal-insulation boards and underlay components are coordinated.",
  "Mevcut çatıda kaplama öncesi hazırlık, su yalıtım örtüsü ve lata yerleşiminin uygulandığı yenileme çalışması.": "A renovation project covering pre-covering preparation, waterproofing membrane and batten placement on an existing roof.",
  "Yapının mimari karakteriyle uyumlu, tamamlanmış kiremit kaplama ve çatı detayları.": "Completed tile covering and roof details in harmony with the building’s architectural character.",
  "Kiremit, mahya ve tamamlayıcı elemanların birlikte uygulandığı, detay odaklı çatı sistemi çözümü.": "A detail-led roofing-system solution combining tiles, ridge pieces and complementary components.",
  "Taşıyıcı sistem": "Supporting structure", "Sistem detayı": "System detail", "Uygulama aşaması": "Installation stage", "Tamamlanmış proje": "Completed project", "Kaplama ve detay": "Covering and details",
  "Keşif ve ihtiyaç analizi": "Site survey and needs analysis", "Sistem ve malzeme seçimi": "System and material selection", "Uygulama ve kalite kontrol": "Installation and quality control",
  "Yapının mevcut durumu, çatı eğimi, taşıyıcı sistem ve su tahliye detayları sahada değerlendirilir.": "The building’s condition, roof pitch, supporting structure and drainage details are assessed on site.",
  "Projenin teknik gereksinimlerine uygun kaplama, yalıtım ve detay bileşenleri birlikte planlanır.": "Covering, insulation and detail components suited to the project’s technical requirements are planned together.",
  "Uygulama aşamaları takip edilir; kritik birleşim ve sabitleme noktaları teslim öncesi kontrol edilir.": "Installation stages are monitored, and critical junctions and fixings are checked before handover.",
  "Ürünler ve Çözümler": "Products and Solutions", "Fotovoltaik Güneş Enerji Sistemleri": "Photovoltaic Solar-Energy Systems", "Rüzgar Klipsleri": "Wind Clips", "Çatı Kaplama Altı Levhası": "Roof Underlay Board", "Yağmur Suyu Sistemleri": "Rainwater Systems",
  "Eğimli çatı sistemini oluşturan ürünler, uygulama örnekleri ve tamamlayıcı detaylar.": "Products, installation examples and complementary details forming pitched-roof systems.",
  "Çatıya entegre güneş enerjisi çözümlerine ilişkin ürün ve uygulama dokümanları.": "Product and installation documents for roof-integrated solar-energy solutions.",
  "Rüzgar yüklerine karşı sabitleme elemanları ve uygulama prensipleri.": "Fixing components and installation principles for resistance to wind loads.",
  "Kiremit model, renk, yüzey ve teknik özelliklerine ilişkin ürün seçkisi.": "A product selection covering tile models, colours, finishes and technical properties.",
  "Su, ısı ve nem yönetimine katkı sağlayan kaplama altı sistem çözümleri.": "Underlay system solutions that support water, heat and moisture management.",
  "Yağmur suyunun kontrollü toplanması ve yapıdan uzaklaştırılması için elemanlar.": "Components for controlled collection and drainage of rainwater away from the building."
});

const sourceText = new WeakMap<Text, string>();
const sourceAttributes = new WeakMap<Element, Record<string, string>>();
const normalise = (value: string) => value.replace(/\s+/g, " ").trim();
const tr = Object.fromEntries(Object.entries(en).map(([turkish, english]) => [english, turkish]));
const richCopy: Record<string, Record<Locale, string>> = {
  "home-hero": { tr: "Antalya&apos;nın<br>Güvenilir<br>Çatı Çözüm Ortağı", en: "Antalya&apos;s<br>Trusted<br>Roofing Solutions Partner" },
  "services-hero": { tr: "İhtiyacınıza uygun<br>profesyonel<br>çatı çözümleri.", en: "Professional<br>roofing solutions<br>tailored to your needs." },
  "projects-hero": { tr: "Gerçek projeler,<br>gerçek çatı çözümleri.", en: "Real projects,<br>considered roofing solutions." },
  "about-hero": { tr: "Çatı konusunda<br><span class=\"text-[#D46A76]\">uzmanlığımız.</span>", en: "Roofing<br><span class=\"text-[#D46A76]\">expertise.</span>" },
  "contact-hero": { tr: "Projenizi<br>birlikte konuşalım<span class=\"text-[#A91F2D]\">.</span>", en: "Let&apos;s discuss<br>your project<span class=\"text-[#A91F2D]\">.</span>" },
  "catalogues-hero": { tr: "Teknik dokümanlara doğrudan erişim.", en: "Direct access to technical documents." },
};

function applyLocale(locale: Locale) {
  document.querySelectorAll<HTMLElement>("[data-i18n-rich]").forEach((element) => {
    const copy = richCopy[element.dataset.i18nRich ?? ""];
    if (copy) element.innerHTML = copy[locale];
  });
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  nodes.forEach((node) => {
    if (node.parentElement?.closest('[data-localized="true"]')) return;
    if (["SCRIPT", "STYLE"].includes(node.parentElement?.tagName ?? "")) return;
    const source = sourceText.get(node) ?? node.nodeValue ?? "";
    sourceText.set(node, source);
    const translation = locale === "en" ? en[normalise(source)] : tr[normalise(source)];
    if (!translation) { node.nodeValue = source; return; }
    node.nodeValue = `${source.match(/^\s*/)?.[0] ?? ""}${translation}${source.match(/\s*$/)?.[0] ?? ""}`;
  });
  document.querySelectorAll<HTMLElement>("[placeholder], [title]").forEach((element) => {
    const sources = sourceAttributes.get(element) ?? {};
    ["placeholder", "title"].forEach((attribute) => {
      const source = sources[attribute] ?? element.getAttribute(attribute);
      if (!source) return;
      sources[attribute] = source;
      const translation = locale === "en" ? en[normalise(source)] : tr[normalise(source)];
      element.setAttribute(attribute, translation ?? source);
    });
    sourceAttributes.set(element, sources);
  });
  document.documentElement.lang = locale;
}

export default function LanguageToggle({ className = "" }: { className?: string }) {
  const [locale, setLocale] = useState<Locale>("tr");
  const pathname = usePathname();
  useEffect(() => {
    applyLocale(locale);
    // Server-rendered page content can hydrate after the navigation bar. Apply
    // once more after hydration so that it cannot overwrite the selected locale.
    const timer = window.setTimeout(() => applyLocale(locale), 500);
    return () => window.clearTimeout(timer);
  }, [locale, pathname]);
  const change = (next: Locale) => { if (next !== locale) setLocale(next); };
  return <div aria-label="Language selector" className={`hidden items-center gap-1 text-[11px] font-bold sm:flex ${className}`}><button type="button" aria-label="Türkçe" aria-pressed={locale === "tr"} onClick={() => change("tr")} className={`relative flex items-center gap-1 px-1 py-2 transition ${locale === "tr" ? "text-white after:absolute after:bottom-0 after:left-1 after:right-1 after:h-px after:bg-[#D46A76]" : "text-white/55 hover:text-white"}`}><span aria-hidden="true" className="text-base leading-none">🇹🇷</span><span>TR</span></button><span aria-hidden="true" className="text-white/25">/</span><button type="button" aria-label="English" aria-pressed={locale === "en"} onClick={() => change("en")} className={`relative flex items-center gap-1 px-1 py-2 transition ${locale === "en" ? "text-white after:absolute after:bottom-0 after:left-1 after:right-1 after:h-px after:bg-[#D46A76]" : "text-white/55 hover:text-white"}`}><span aria-hidden="true" className="text-base leading-none">🇬🇧</span><span>EN</span></button></div>;
}
